name: Data point feature request
description: Suggest adding data points for telemetry purpose
body:
  - type: textarea
    id: change-log
    attributes:
      label: Changelog Entry
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    id: sample-telemetrics
    attributes:
      label: Design
  - type: textarea
    id: specific-changes
    attributes:
      label: Specific change
