name: Telemetry request
description: Suggest a telemetry data point
labels:
  - area-telemetry
  - feature-request
  - customer-reported
  - Bot Services
body:
  - type: markdown
    attributes:
      value: |
        ## Please read before submitting a feature request

        Web Chat is a client-side JavaScript library and emit telemetry data. However, we *do not collect them*. It is up to web developers to [connect their data collector to Web Chat](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/04.api/k.telemetry-application-insights) and collect data for their own use. We do not govern and do not know how these data are being used.

        Ultimately, web developers can always fork Web Chat source code and collect any data in their own forked version, regardless whether data points are in the official source code or not.

        Some services and systems at Microsoft use Web Chat, including, but not limited to, Azure Bot Services. They may collect data by connecting their data collector to Web Chat, and/or collect data on service-side. You should always read Privacy Policy to understand how data are collected.

        This feature request template is a best effort to make telemetry more accessible and transparent to everyone. However, web developers may not use feature request to expose what they would collect.
  - type: textarea
    id: sample-scenarios
    attributes:
      label: What do you want to analyze and understand?
      value: |
        - Outgoing message reliability
        - How long it takes to successfully send a message in average
    validations:
      required: true
  - type: textarea
    id: data-point
    attributes:
      label: What new data points do you want to add?
      value: |
        When a message is being sent, emit:
          - Begin to send a message
          - Send status changes from "sending" to "sent", with duration
    validations:
      required: true
  - type: textarea
    id: sample-telemetrics
    attributes:
      label: How these data points being used in analysis?
      value: |
        ### Outgoing message reliability

        $$ outgoing\ message\ reliability = \frac{n_{sent}}{n_{begin}} \times 100\\% $$

        ### Average time to send a message

        $$ average\ time\ to\ send\ a\ message = \frac{\displaystyle\sum_{i=1}^n t_i}{n} $$

        $$ t_x = time\ to\ send\ a\ message $$
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the feature request here.
