name: Telemetry request
description: Suggest a telemetry data point
labels:
  - area-telemetry
  - feature-request
  - customer-reported
  - Bot Services
body:
  - type: markdown
    attributes:
      value: |
        ## Please read before submitting a feature request

        Web Chat is a client-side JavaScript library and emit telemetry data. However, we *do not collect them*. It is up to web developers to [connect their data collector to Web Chat](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/04.api/k.telemetry-application-insights) and collect data for their own use. We do not govern and do not know how these data are being used.

        Ultimately, web developers can always fork Web Chat source code and collect any data in their own forked version, regardless whether data points are in the official source code or not.

        Some services and systems at Microsoft use Web Chat, including but not limited to Azure Bot Services. They may collect data by connecting their data collector to Web Chat. This does not implies Web Chat collect data. You should always read Privacy Policy to understand more about data collection.

        This feature request template is to make telemetry data more accessible and transparent to everyone. However, web developers may not use feature request to expose what they would collect.
  - type: textarea
    id: sample-scenarios
    attributes:
      label: What do you want to analyze and understand?
      value: |
        - Outgoing message reliability
        - In average, how long it takes to successfully send a message
    validations:
      required: true
  - type: textarea
    id: data-point
    attributes:
      label: What new data points do you want to add?
      value: |
        When a message is being sent, emit:
          - Begin of sending a message
          - Send status changes from "sending" to "sent", with duration
          - Send status changes from "sending" to "send failed", with duration
    validations:
      required: true
  - type: textarea
    id: sample-telemetrics
    attributes:
      label: Can you give us the sample usages of the data points?
      value: |
        $$ outgoing\ message\ reliability = {number\ of\ send\ status\ changed\ from\ sending\ to\ sent \over number\ of\ begin\ of\ send\ message} \times 100\\% $$
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the feature request here.
