name: Telemetry request
description: Suggest a telemetry data point
labels:
  - area-telemetry
  - feature-request
  - customer-reported
  - Bot Services
body:
  - type: markdown
    attributes:
      value: |
        ## Please read

        Web Chat emit telemetry. However, we *do not collect them* and there is no default collector. It is up to web developers to [connect their telemetry collection system to Web Chat](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/04.api/k.telemetry-application-insights) and collect telemetry for their own use. We do not govern and do not know how these data are being used.
        
        Web developers can always modify our source code and collect what they want, regardless whether a telemetry data point is added to Web Chat or not.

        This feature request is to make telemetry data more accessible and transparent to everyone.
  - type: textarea
    id: sample-scenarios
    attributes:
      label: What do you want to understand with this new data points?
      value: |
        This new data point will give us ability to measure:
        - Outgoing message reliability
        - In average, how long it takes to successfully send a message
    validations:
      required: true
  - type: textarea
    id: data-point
    attributes:
      label: What new data points do you want to add?
      value: |
        When a message is being sent, emit:
          - Begin of sending a message
          - Send status changes from "sending" to "sent", with duration
          - Send status changes from "sending" to "send failed", with duration
    validations:
      required: true
  - type: textarea
    id: sample-telemetrics
    attributes:
      label: Can you give us the sample usages of the data points?
      value: |
        $$ outgoing\ message\ reliability = {number\ of\ send\ status\ changed\ from\ sending\ to\ sent \over number\ of\ begin\ of\ send\ message} \times 100\\% $$
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
