name: Telemetry request
description: Suggest a telemetry data point
labels:
  - area-telemetry
  - feature-request
  - customer-reported
  - Bot Services
body:
  - type: markdown
    attributes:
      value: |
        ## Please read before submitting a feature request

        Web Chat is a client-side JavaScript library and emit telemetry. However, we *do not collect them* and no collectors are connected by default. It is up to web developers to [connect their telemetry collection system to Web Chat](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/04.api/k.telemetry-application-insights) and collect telemetry for their own use. We do not govern and do not know how these data are being used.

        Web developers can always modify our source code and collect everything they want, regardless whether telemetry data points are added to Web Chat or not.

        Some services and systems at Microsoft use Web Chat. They may collect telemetry data by connecting telemetry collector to Web Chat. This does not implies Web Chat collect data.

        This feature request is to make telemetry data more accessible and transparent to everyone. However, web developers may not use feature request and may not tell us what data they collect.
  - type: textarea
    id: sample-scenarios
    attributes:
      label: What do you want to understand with this new data points?
      value: |
        - Outgoing message reliability
        - In average, how long it takes to successfully send a message
    validations:
      required: true
  - type: textarea
    id: data-point
    attributes:
      label: What new data points do you want to add?
      value: |
        When a message is being sent, emit:
          - Begin of sending a message
          - Send status changes from "sending" to "sent", with duration
          - Send status changes from "sending" to "send failed", with duration
    validations:
      required: true
  - type: textarea
    id: sample-telemetrics
    attributes:
      label: Can you give us the sample usages of the data points?
      value: |
        $$ outgoing\ message\ reliability = {number\ of\ send\ status\ changed\ from\ sending\ to\ sent \over number\ of\ begin\ of\ send\ message} \times 100\\% $$
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the feature request here.
